
export interface EmojiCategory {
    id: string;
    title: string;
    items: Emoji[];
}

/**
 * Different emoji types have different presentational characteristics.
 * - normal: The emoji has no variations
 * - keycap: Used for numbers 0-10, number sign (#), asterisk (*)
 * - flag: National flags
 * - regional: The Regional Indicator characters
 * - variant: Characters that may be followed by U+fe0f (VS16, request color emoji presentation) 
 *   but cannot be followed by U+fe0e (VS15, request monochrome non-emoji presentation)
 * - diversity: The emoji supports skintone variation. Typically this is <unicode> <zwj> <skintone-modifier>,
 *   but multiDiversityBaseSame can be present to specify a different sequence (where "skintone" can be any 
 *   skintone modifier)
 * - variant,diversity: Character has the variant and diversity properties
 * - text-default: Must be followd by VS16 (request emoji presentation) to be emojis. The bare character 
 *   is text by default.
 * - multi-diversity: Emoji can be variated by two (or more) skintones. For these, consult 
 *   multiDiversityBaseDifferent to construct diverse variations. Typically multiDiversityBaseSame will also
 *   be available for setting a single skintone for both values (which is more space efficient).
 * - directional,diversity: Emoji supports a single skintone modifier and the glyph direction can be changed using 
 *   <character> <zwj> <left/right arrow>. See Unicode TR-51 section 2.10 for more information.
 */
export type EmojiType = 'normal' | 'keycap' | 'flag' | 'regional' | 'variant' | 'diversity' | 'variant,diversity'
    | 'text-default' | 'multi-diversity' | 'directional,diversity';

export interface Emoji {
    /**
     * The actual character(s). Can be used directly.
     */
    string: string;

    /**
     * The raw Unicode codepoints.
     */
    unicode: number[];

    /**
     * The Unicode codepoints as a dash-separated string (X-Y-Z).
     */
    unicodeString: string;

    /**
     * A short keyword that can be used as a :shortcut: for this emoji.
     * Not all emoji have these.
     */
    shortcut?: string;

    /**
     * A short textual description. Not all emoji have this
     */
    description?: string;

    /**
     * A list of descriptive keywords. Not all emoji have these.
     */
    keywords?: string[];

    /**
     * Whether its recommended to exclude this emoji from the emoji picker.
     */
    excludeFromPicker?: boolean;

    /**
     * The type of this emoji. See EmojiType for details.
     */
    type: EmojiType;

    /**
     * Provides a pattern for producing a single-skintone diverse variant of this 
     * emoji. Replace the "skintone" component with one of the Fitzpatrick skin tone modifiers.
     */
    multiDiversityBaseSame?: string;

    /**
     * Provides a pattern for producing a two-skintone diverse variant of this 
     * emoji. Replace the "skintone" components with Fitzpatrick skin tone modifiers.
     */
    multiDiversityBaseDifferent?: string;

    multiDiversityBaseDifferentIsSorted?: boolean;
}

export type EmojiImageResolver = (iconId: string, options: any, variant?: string) => string;
export type EmojiParserAttributesCallback = (rawText: string, iconId: string) => Record<string, string>;

/**
 * Specifies options for @/emoji's EmojiParser class.
 */
export interface EmojiParserOptions {
    /**
     * Used to determine the image URL to use for the emoji. 
     */
    resolveImage?: EmojiImageResolver;

    /**
     * Where to load image assets from. The image assets are provided within this package,
     * but you will have to configure your web server to serve them from within node_modules
     * or otherwise extract them. See README for more details.
     */
    baseUrl?: string;

    /**
     * The image type to use, as the suffix of the assets. The default is ".png".
     */
    imageType?: string;

    /**
     * The size to use. This is expected to be in the form "NxM", but if you specify "N" it will 
     * be automatically converted to "NxN". The default is "72x72".
     */
    size?: string;

    /**
     * A class to assign to <img> elements generated by this parser.
     */
    className?: string;
    onLoadError?: (event: ErrorEvent) => void;

    /**
     * Custom attributes to add to <img> tags made for emoji
     */
    decorateAttributes?: (rawText: string, iconId: string) => Record<string, string>;
}
