
export interface EmojiCategory {
    id: string;
    title: string;
    items: Emoji[];
}

/**
 * Different emoji types have different encoding characteristics in Unicode. This is meant to 
 * bifurcate emojis along those lines. You can use these for emoji picker categories if you want,
 * but you may want to use other categorizations.
 */
export type EmojiType = 'normal' | 'keycap' | 'flag' | 'regional' | 'variant' | 'diversity' | 'variant,diversity'
    | 'text-default' | 'multi-diversity';

export interface Emoji {
    /**
     * The actual character(s). Can be used directly.
     */
    string: string;

    /**
     * The raw Unicode codepoints.
     */
    unicode: number[];

    /**
     * A short textual description
     */
    description: string;

    /**
     * A list of descriptive keywords
     */
    keywords: string[];

    /**
     * Whether its recommended to exclude this emoji from the emoji picker.
     */
    excludeFromPicker: boolean;

    /**
     * The type of this emoji. See EmojiType for details.
     */
    type: EmojiType;

    multiDiversityBaseSame?: string;
    multiDiversityBaseDifferent?: string;
    multiDiversityBaseDifferentIsSorted: boolean;
}

export type EmojiImageResolver = (iconId: string, options: any, variant?: string) => string;
export type EmojiParserAttributesCallback = (rawText: string, iconId: string) => Record<string, string>;

/**
 * Specifies options for @/emoji's EmojiParser class.
 */
export interface EmojiParserOptions {
    /**
     * Used to determine the image URL to use for the emoji. 
     */
    resolveImage?: EmojiImageResolver;

    /**
     * Where to load image assets from. The image assets are provided within this package,
     * but you will have to configure your web server to serve them from within node_modules
     * or otherwise extract them. See README for more details.
     */
    baseUrl?: string;

    /**
     * The image type to use, as the suffix of the assets. The default is ".png".
     */
    imageType?: string;

    /**
     * The size to use. This is expected to be in the form "NxM", but if you specify "N" it will 
     * be automatically converted to "NxN". The default is "72x72".
     */
    size?: string;

    /**
     * A class to assign to <img> elements generated by this parser.
     */
    className?: string;
    onLoadError?: (event: ErrorEvent) => void;

    /**
     * Custom attributes to add to <img> tags made for emoji
     */
    decorateAttributes?: (rawText: string, iconId: string) => Record<string, string>;
}
